n = input('digite algo: ')
print(f'O tipo primitivo desse valor é {type(n)}')
print(f'Só tem espaços? {n.isspace()}')
print(f'É um número? {n.isnumeric()}')
print(f'É alfabeto? {n.isalpha()}')
print(f'Está em letra maiúscula? {n.isupper()}')
print(f'Está em letra minúscula? {n.islower()}')
print(f'Está capitalizado? {n.istitle()}')